name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ”¨ Breaking Changes'
    labels:
      - 'breaking'
  - title: 'ğŸš€ Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
      - 'improvement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: 'ğŸ§° Maintenance'
    labels: 
      - 'chore'
      - 'refactor'
      - 'style'
      - 'test'
      - 'docs'
      - 'ci'
      - 'perf'
      - 'build'
      - 'revert'
      - 'release'
      - 'wip'
      - 'cleanup'
  - title: 'ğŸ“ Documentation'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
    title:
      - '/feat/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
  - label: 'breaking'
    body:
      - '/breaking change/i'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES